#!/bin/bash

# Make sure curl is available
clear
echo "Installing/updating curl if necessary..."
yum install -y curl > /dev/null

# Identify email account to associate with the key
if [ $# -eq 0 ]
  then
    read -p "Email address to associate with the git SSH key: " email 
    while true; do
      read -p "Is $email correct? (y/n) " yn
      case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer (y)es or (n)o.";;
      esac
    done
  else
    email = $1
fi
clear


sshfile="id_rsa"
if [ $# -eq 1 ]
  then
    sshfile=$2
fi

# Create a new git SSH cert for use with external services.
clear
echo "Creating certificate"
cd ~/.ssh
ssh-keygen -t rsa -C "$email" -N "" -f ~/.ssh/$sshfile
ssh-add ~/.ssh/$sshfile
clear

# Optionally add the certificate to a remote git account
echo "Which remote git service will this certificate be used with?"
echo "[0] None"
echo "[1] Github"
echo "[2] BitBucket"
read -p "Service: " svc

# Read the key from its file
keycontent=$(<~/.ssh/$sshfile.pub)

while true; do
  case $svc in
    0 ) echo "The public key is available at ~/.ssh/$sshfile.pub"
        exit;;
    1 ) read -p "Github Username: " user
        read -p "Github Password: " pass
        clear
        echo "Adding SSH certificate to Github for $user..."
        break;;
    2 ) read -p "BitBucket Username: " user
        read -p "BitBucket Password: " pass
        clear
        echo "Adding SSH certificate to BitBucket for $user..."
        curl -X POST --user $user:$pass https://bitbucket.org/api/1.0/users/$user/ssh-keys --data-urlencode "accountname=$user&label=$(hostname) server&key=$keycontent"
        clear
        ssh -T git@bitbucket.org
        echo "accountname=$user&label=$(hostname) server&key=$keycontent" 
        break;;
    * ) echo "Please select a service:"
        echo "[0] None"
        echo "[1] Github"
        echo "[2] BitBucket";;
  esac
done